import React from "react";
export type IconType = (size: [number, number], colors: string[], id?: string | number) => React.ReactNode;

export { alarm } from "./alarm";
export { arrowUpRight } from "./arrowUpRight";
export { calendar } from "./calendar";
export { cart } from "./cart";
export { catalogMenu } from "./catalogMenu";
export { check } from "./check";
export { chevronDown } from "./chevronDown";
export { chevronLeft } from "./chevronLeft";
export { chevronRight } from "./chevronRight";
export { chevronUp } from "./chevronUp";
export { close } from "./close";
export { deliveryCourier } from "./deliveryCourier";
export { deliverySelfpickup } from "./deliverySelfpickup";
export { exclamationCircle } from "./exclamationCircle";
export { exclamationMark } from "./exclamationMark";
export { exclamationTriangle } from "./exclamationTriangle";
export { heart } from "./heart";
export { heartFilled } from "./heartFilled";
export { logout } from "./logout";
export { minus } from "./minus";
export { novelty } from "./novelty";
export { orders } from "./orders";
export { pencil } from "./pencil";
export { percent } from "./percent";
export { phone } from "./phone";
export { plus } from "./plus";
export { repeat } from "./repeat";
export { ruble } from "./ruble";
export { search } from "./search";
export { sort } from "./sort";
export { trash } from "./trash";
export { user } from "./user";
export { warning } from "./warning";
