import React from "react";
export type IconType = (size: [number, number], colors: string[], id?: string | number) => React.ReactNode;

export { cart } from "./cart";
export { catalogMenu } from "./catalogMenu";
export { check } from "./check";
export { chevronDown } from "./chevronDown";
export { chevronLeft } from "./chevronLeft";
export { chevronRight } from "./chevronRight";
export { chevronUp } from "./chevronUp";
export { close } from "./close";
export { delivery } from "./delivery";
export { exclamationMark } from "./exclamationMark";
export { heart } from "./heart";
export { heartFilled } from "./heartFilled";
export { minus } from "./minus";
export { novelty } from "./novelty";
export { percent } from "./percent";
export { phone } from "./phone";
export { plus } from "./plus";
export { ruble } from "./ruble";
export { search } from "./search";
export { sort } from "./sort";
export { trash } from "./trash";
export { user } from "./user";
export { warning } from "./warning";
