export const COLORS = {
    WHITE: '#FFFFFF',
    BLACK_ALIKE: '#444449',
    BORDER: '#A9B9DE',
    LIGHT_BLUE: '#EEF7FF',
    GRAY_PRIMARY: '#687CAB',
    GRAY_SECONDARY: '#A9B9DE',
    GREEN_PRIMARY: '#00A3B3',
    GREEN_SECONDARY: '#007C81',
    RED_PRIMARY: '#E31E24',
    TRANSPARENT: 'transparent',
};
