export const CATALOG_LETTERS: { id: string, name: string, value: string[] }[] = [
    { id: 'А', name: 'А', value: ['А'] },
    { id: 'Б', name: 'Б', value: ['Б'] },
    { id: 'В', name: 'В', value: ['В'] },
    { id: 'Г', name: 'Г', value: ['Г'] },
    { id: 'Д', name: 'Д', value: ['Д'] },
    { id: 'Е', name: 'Е', value: ['Е'] },
    { id: 'Ж', name: 'Ж', value: ['Ж'] },
    { id: 'З', name: 'З', value: ['З'] },
    { id: 'И', name: 'И', value: ['И'] },
    { id: 'К', name: 'К', value: ['К'] },
    { id: 'Л', name: 'Л', value: ['Л'] },
    { id: 'М', name: 'М', value: ['М'] },
    { id: 'Н', name: 'Н', value: ['Н'] },
    { id: 'О', name: 'О', value: ['О'] },
    { id: 'П', name: 'П', value: ['П'] },
    { id: 'Р', name: 'Р', value: ['Р'] },
    { id: 'С', name: 'С', value: ['С'] },
    { id: 'Т', name: 'Т', value: ['Т'] },
    { id: 'У', name: 'У', value: ['У'] },
    { id: 'Ф', name: 'Ф', value: ['Ф'] },
    { id: 'Х', name: 'Х', value: ['Х'] },
    { id: 'Ц', name: 'Ц', value: ['Ц'] },
    { id: 'Ч', name: 'Ч', value: ['Ч'] },
    { id: 'Ш', name: 'Ш', value: ['Ш'] },
    { id: 'Щ', name: 'Щ', value: ['Щ'] },
    { id: 'Э', name: 'Э', value: ['Э'] },
    { id: 'Ю', name: 'Ю', value: ['Ю'] },
    { id: 'Я', name: 'Я', value: ['Я'] },
    { id: '0-9', name: '0-9', value: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'] },
    {
        id: 'А-Z',
        name: 'А-Z',
        value: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'z', 'x', 'c', 'v', 'b', 'n', 'm']
    },
];
