version: '3'
services:
    nextjs:
        restart: 'always'
    nginx:
        restart: 'always'
        volumes:
            - './nginx/http.password.conf:/config/nginx/site-confs/default.conf'
            - './nginx/.htpasswd:/config/nginx/.htpasswd'
