version: '3'
services:
    nextjs:
        restart: 'always'
    nginx:
        image: 'lscr.io/linuxserver/swag:latest'
        restart: 'always'
        environment:
            - 'PUID=1000'
            - 'PGID=1000'
            - 'TZ=Europe/London'
            - 'URL=${DOMAIN}'
            - 'SUBDOMAINS='
            - 'VALIDATION=http'
        volumes:
            - './nginx/https.password.conf:/config/nginx/site-confs/default.conf'
            - './nginx/.htpasswd:/config/nginx/.htpasswd'
