version: '3'
services:
    redis:
        image: 'redis:alpine'
        restart: 'always'
        command: 'redis-server --requirepass ${REDIS_PASSWORD}'
        ports:
            - '${REDIS_PORT}:6379'
